### ISSUE TITLE
[Backend] Create Logan

### ISSUE THREAD

**Issue by akslaym** [BPR-Data-Team/Election-Night#132]
Plan:
- Primary_Key: State_OfficeType_District
- Called

Create lambda function that resends all data to a dynamoDB table that Logan will edit and re-push each time he calls a race. He will hit "deploy"

Then create a dynamo stream function that will be called each time Logan updates the data and send new image to frontend

**Comment by isabelleashapiro** [comment]
Currently have logan's lambda function up and running, just need to create dynamo stream function as well.
Note: takes about 15 seconds to run so maybe this is not the most efficient schema but maybe we don't care?

**Comment by isabelleashapiro** [comment]
Currently made batch window for stream 10 seconds and batch size 50 (highly doubt we will be calling 50 races at once), not sure if there's a more reasonable way to do this

**Comment by isabelleashapiro** [comment]
Logan seems to be done.
