### ISSUE TITLE
[ALL] Create 24cast.org logo

### ISSUE THREAD

**Issue by akslaym** [BPR-Data-Team/Election-Night#27]

**Comment by arielshif** [comment]
what does this mean? our logo is just the name typed in gelica font. you can pull styling directly from the main site navbar:
https://github.com/BPR-Data-Team/ElectionModel2024-site/blob/main/src/components/Nav.tsx#L50-L57
https://github.com/BPR-Data-Team/ElectionModel2024-site/blob/main/src/app/(main)/globals.css#L83-L89
